### PR TITLE
cleanup tornado application

### PR DESCRIPTION
**Pull request by aabadie**
- avoid using class attributes with the websocket handler
- move server and ioloop start in the main murdock module
- don't declare handlers as nested class
- don't use 's' variable but standard 'self' instead
- main tornado application is now in charge of broadcasting the websocket messages and keep alive pings

### CODE REVIEW

**Comment by aabadie** [comment]
I also think that the `lock` attribute could be removed but I haven't tried (and don't know how).
Same for the keep alive messaging code: Tornado should be able to handle that using the `websocket_ping_interval` of the tornado application.

**Comment by aabadie** [comment]
Ok, I noticed that this PR is breaking other things. Well, Mudock code requires more refactoring than I initially thought unfortunately.

**Comment by kaspar030** [comment]
> my eyes are bleeding when I read murdock.py

thanks for going through all the pain.

If you want any of these improvements integrated, I suggest sticking to best-practices and cutting them into pieces.

**Comment by kaspar030** [comment]
> Mudock code requires more refactoring than I initially thought unfortunately.

What are you trying to achieve?

**Comment by aabadie** [comment]
>  I suggest sticking to best-practices and cutting them the PR into pieces.

This PR is already one piece (apart from the harmless PEP8 changes) => it 'just' cleans up the Tornado application and its integration into the rest of the code. It would be great to test it to see if it introduces any regression or error.

> What are you trying to achieve?

1. Better understand how Murdock works
2. Since Murdock is written in Python, apply Python programming best practices. Some people did some advertisement of it in scientific paper, the code have to be improved
3. Refactor the PullRequest class (probably split it in pieces)
4. Add tests. For the Tornado part, this is easy with `tornado.testing`. Configure a CI (Travis or CircleCI). Configure checks for PEP8 and maybe lint issues.

In the end, that sounds like rewriting Murdock ;)

**Comment by aabadie** [comment]
> I suggest sticking to best-practices and cutting the PR into pieces.

I'll do that

**Comment by aabadie** [comment]
@kaspar030, I started to split this PR in smaller pieces: see #26, #25, #27 and #28.
I have other refactoring/improvements in mind but I'd like them merged first.

**Pull request closed without merging**
